title: CEDA Archive 
description: CEDA Archive site implemented using Jekyll.
show_excerpts: true

plugins:
  - jekyll-feed



destination: docs

# Turn on built-in syntax highlighting.
highlighter: rouge
